vim.cmd("set showmatch")
vim.cmd("set mouse=v")
vim.cmd("set hlsearch")
vim.cmd("set incsearch ")
vim.cmd("set tabstop=4 ")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set expandtab")
vim.cmd("set number")
vim.cmd("set mouse=a")
vim.cmd("set ttyfast")
vim.cmd("set autoindent")
vim.cmd("set cursorline")
